version: 2
jobs:
  build:
    docker:
      - image: archlinux/base:latest
    steps:
      - checkout
      - run: pacman -Syu --noconfirm texlive-core
      - run: pwd
      - run: pdflatex resume.tex
      - store_artifacts:
          path: /root/project/resume.pdf
