version: 2
jobs:
  build:
    docker:
      - image: archlinux/base:latest
    steps:
      - checkout
      - run: pacman -Syu --noconfirm texlive-core jq curl git openssh
      - run: pdflatex resume.tex
      - store_artifacts:
          path: /root/project/resume.pdf
      - run: echo "# My CV" > README.md
      - run: echo "[Download](https://$CIRCLE_BUILD_NUM-31460429-gh.circle-artifacts.com/0/root/project/resume.pdf)">>README.md
      - run: echo "[![CircleCI](https://circleci.com/gh/psamim/cv.svg?style=svg)](https://circleci.com/gh/psamim/cv)">>README.md
      - run: git config user.email "psamim@gmail.com"
      - run: git config user.name "CirlceCI"
      - run: git add README.md && git commit -m 'Update [skip ci]'
      - run: mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: git push origin HEAD:master
